python-version = "3.13.0"
preset = "legacy"

[[sub-config]]
matches = "app/models/schemas"

[sub-config.errors]
no-matching-overload = "ignore"

[[sub-config]]
matches = "app/graphql/schema.py"

[sub-config.errors]
inconsistent-inheritance = "ignore"
