"""add_metrics_tables

Revision ID: 1e3305a06ba4
Revises: 
Create Date: 2025-12-19 23:04:22.431345+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '1e3305a06ba4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tables may already exist if the DB was bootstrapped outside Alembic or
    # alembic_version was reset. Skip CREATE TABLE when present; use IF NOT EXISTS
    # for indexes so reruns and partial states do not fail.
    bind = op.get_bind()
    insp = inspect(bind)

    def has_table(name: str) -> bool:
        return inspect(bind).has_table(name)

    # ### commands auto generated by Alembic - please adjust! ###
    if not insp.has_table('benchmark_runs'):
        op.create_table('benchmark_runs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('run_type', sa.String(), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('streaming', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if has_table('benchmark_runs'):
        op.create_index('idx_benchmark_runs_created_at', 'benchmark_runs', ['created_at'], unique=False, if_not_exists=True)
        op.create_index('idx_benchmark_runs_status', 'benchmark_runs', ['status'], unique=False, if_not_exists=True)
    if not insp.has_table('error_logs'):
        op.create_table('error_logs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('benchmark_run_id', sa.String(), nullable=True),
        sa.Column('error_type', sa.String(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=False),
        sa.Column('error_details', sa.JSON(), nullable=True),
        sa.Column('request_url', sa.String(), nullable=True),
        sa.Column('request_method', sa.String(), nullable=True),
        sa.Column('request_headers', sa.JSON(), nullable=True),
        sa.Column('request_body', sa.JSON(), nullable=True),
        sa.Column('response_status', sa.Integer(), nullable=True),
        sa.Column('response_headers', sa.JSON(), nullable=True),
        sa.Column('response_body', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    if has_table('error_logs'):
        op.create_index('idx_error_logs_benchmark_run', 'error_logs', ['benchmark_run_id'], unique=False, if_not_exists=True)
        op.create_index('idx_error_logs_created_at', 'error_logs', ['created_at'], unique=False, if_not_exists=True)
        op.create_index('idx_error_logs_error_type', 'error_logs', ['error_type'], unique=False, if_not_exists=True)
        op.create_index('idx_error_logs_provider', 'error_logs', ['provider'], unique=False, if_not_exists=True)
    if not insp.has_table('provider_metrics'):
        op.create_table('provider_metrics',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('benchmark_run_id', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('ttft', sa.Float(), nullable=True),
        sa.Column('total_time', sa.Float(), nullable=False),
        sa.Column('prompt_tokens', sa.Integer(), nullable=True),
        sa.Column('completion_tokens', sa.Integer(), nullable=True),
        sa.Column('total_tokens', sa.Integer(), nullable=True),
        sa.Column('tokens_per_second', sa.Float(), nullable=True),
        sa.Column('request_size_bytes', sa.Integer(), nullable=True),
        sa.Column('response_size_bytes', sa.Integer(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_type', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('response_data', sa.JSON(), nullable=True),
        sa.Column('extra_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if has_table('provider_metrics'):
        op.create_index('idx_provider_metrics_benchmark_run', 'provider_metrics', ['benchmark_run_id'], unique=False, if_not_exists=True)
        op.create_index('idx_provider_metrics_created_at', 'provider_metrics', ['created_at'], unique=False, if_not_exists=True)
        op.create_index('idx_provider_metrics_model', 'provider_metrics', ['model'], unique=False, if_not_exists=True)
        op.create_index('idx_provider_metrics_provider', 'provider_metrics', ['provider'], unique=False, if_not_exists=True)
        op.create_index('idx_provider_metrics_success', 'provider_metrics', ['success'], unique=False, if_not_exists=True)
    if not insp.has_table('latency_history'):
        op.create_table('latency_history',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('provider_metric_id', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('ttft', sa.Float(), nullable=True),
        sa.Column('total_time', sa.Float(), nullable=False),
        sa.Column('tokens_per_second', sa.Float(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('period', sa.String(), nullable=True),
        sa.Column('period_start', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['provider_metric_id'], ['provider_metrics.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if has_table('latency_history'):
        op.create_index('idx_latency_history_created_at', 'latency_history', ['created_at'], unique=False, if_not_exists=True)
        op.create_index('idx_latency_history_model', 'latency_history', ['model'], unique=False, if_not_exists=True)
        op.create_index('idx_latency_history_period_start', 'latency_history', ['period_start'], unique=False, if_not_exists=True)
        op.create_index('idx_latency_history_provider', 'latency_history', ['provider'], unique=False, if_not_exists=True)
        op.create_index('idx_latency_history_provider_model_period', 'latency_history', ['provider', 'model', 'period', 'period_start'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_latency_history_provider_model_period', table_name='latency_history', if_exists=True)
    op.drop_index('idx_latency_history_provider', table_name='latency_history', if_exists=True)
    op.drop_index('idx_latency_history_period_start', table_name='latency_history', if_exists=True)
    op.drop_index('idx_latency_history_model', table_name='latency_history', if_exists=True)
    op.drop_index('idx_latency_history_created_at', table_name='latency_history', if_exists=True)
    op.drop_table('latency_history')
    op.drop_index('idx_provider_metrics_success', table_name='provider_metrics', if_exists=True)
    op.drop_index('idx_provider_metrics_provider', table_name='provider_metrics', if_exists=True)
    op.drop_index('idx_provider_metrics_model', table_name='provider_metrics', if_exists=True)
    op.drop_index('idx_provider_metrics_created_at', table_name='provider_metrics', if_exists=True)
    op.drop_index('idx_provider_metrics_benchmark_run', table_name='provider_metrics', if_exists=True)
    op.drop_table('provider_metrics')
    op.drop_index('idx_error_logs_provider', table_name='error_logs', if_exists=True)
    op.drop_index('idx_error_logs_error_type', table_name='error_logs', if_exists=True)
    op.drop_index('idx_error_logs_created_at', table_name='error_logs', if_exists=True)
    op.drop_index('idx_error_logs_benchmark_run', table_name='error_logs', if_exists=True)
    op.drop_table('error_logs')
    op.drop_index('idx_benchmark_runs_status', table_name='benchmark_runs', if_exists=True)
    op.drop_index('idx_benchmark_runs_created_at', table_name='benchmark_runs', if_exists=True)
    op.drop_table('benchmark_runs')
    # ### end Alembic commands ###
